// <auto-generated />
namespace MyProjectV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class contrat_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contrat_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201606280925161_contrat_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
